# Sunucu Portu
server.port=8080

# H2 Dosya Tabanlı Veritabanı Ayarları (Kapanınca Silinmez!)
# Proje klasörünün içine "stok_verileri.mv.db" adında bir dosya açar ve verileri buraya kaydeder.
spring.datasource.url=jdbc:h2:file:./stok_verileri
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Hibernate Ayarları
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Swagger UI Ayarları
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

spring.jackson.date-format=yyyy-MM-dd HH:mm:ss
spring.jackson.time-zone=Europe/Istanbul
# LocalDateTime kullanılıyorsa seri üretimi düzeltmek için:
spring.jackson.serialization.write-dates-as-timestamps=false
